services:
  - type: web
    name: emotion-analyzer
    env: python
    buildCommand: ""
    startCommand: gunicorn emotion_server:app
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
